<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
    <xacro:property name="chassis_length" value="0.32"/>
    <xacro:property name="chassis_width" value="0.15"/>
    <xacro:property name="chassis_height" value="0.07"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.0175"/>
    <xacro:property name="wheel_thickness" value="0.03"/>
    <xacro:property name="wheel_mass" value="0.4"/>
    <xacro:property name="wheel_offset_x" value="0"/>
    <xacro:property name="wheel_offset_y" value="0.075"/>
    <xacro:property name="wheel_offset_z" value="0"/>
    <xacro:property name="caster_wheel_radius" value="0.0175"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="${chassis_length/2 - caster_wheel_radius}"/>
    <xacro:property name="caster_wheel_offset_z" value="${-chassis_height/2 + wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>
</robot>